### ISSUE TITLE
A default ServiceLimiter implementation

### ISSUE THREAD

**Issue by snakedye** [Byzantium-ETS/lsat#10]
This struct should be used in the demo, tests and serve as a base for people who get started with this project.

## Tasks

* [ ] Create struct that implements ServiceLimiter
* [ ] Add the following fields to Service
    * Price
    * Duration
    * Resource
* [ ] Test the new ServiceLimiter implementation
    
## Acceptance Criteria

* The service needs to be identified by "service_name:tier"
* It needs to support multiple services with tiers
