### ISSUE TITLE
Phoenixd as the first lightning implementation supported

### ISSUE THREAD

**Issue by snakedye** [Byzantium-ETS/lsat#2]
Use [phoenixd](https://github.com/ACINQ/phoenixd) as the lightning node.

### API

* https://phoenix.acinq.co/server/api

### Tasks

* [x] Implement `POST /payinvoice`.
* [x] Implement `POST /createinvoice`.
* [ ] ~~Tests for the phoenix client.~~ (testing an API is too much)
